---
- name: Setting up Workstation as SU 
  hosts: localhost
  become: true
  gather_facts: false
  vars:
       list_of_apts:
          - vagrant
          - virtualbox
          - docker.io
          - docker-compose
          - tree
          - htop
          - iftop
          - nmap
          - sshpass
          - ncdu
          - tmux
          - python-pip
          - python-vagrant
          - nfs-common
  roles:
    - common-apt
  tags:
    - common

- name: Setting up Workstation as local user 
  hosts: localhost
  gather_facts: false
  become: false
  roles:
    - vim
  tags:
    - vim

