---
- name: install apt packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - vagrant
    - virtualbox
    - nfs-common
    - tree
    - htop
    - docker.io
    - docker-compose
    - nmap
    - sshpass
    - ncdu
    - tmux




