---
- name: Setup vundle git repo
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: ~/.vim/bundle/Vundle.vim

- name: Copy vim config 
  copy:
   src: files/.vimrc
   dest: ~/.vimrc
   mode: 0600
   backup: yes
  register: vim_config


- name: Output
  debug:
    msg: "Please run :PluginInstall after you open vim"
  when: vim_config.changed
 
