name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install requirments for build
      run: sudo scripts/ci_bootstrap.sh
    - name: print test matrix out
      working-directory: roles/common-apt/
      run: molecule matrix test -s docker
