name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run apt installs
      run: sudo scripts/ci_bootstrap.sh
    - name: Run pip install
      run: pip install -r requirements.txt
    - name: print test matrix out
      working-directory: roles/common-apt/
      run: molecule matrix test -s docker
    - name: run molecule test
      working-directory: roles/common-apt/
      run: molecule test -s docker
